version: '3.8'

services:
  orcaapp:
    image: orcaapp
    container_name: orcaapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:8080

  cypress:
    image: "cypress/included:4.10.0"
    container_name: cypress
    restart: always
    environment:
      - CYPRESS_baseUrl=http://orcaapp:8080
    depends_on:
      - orcaapp
    working_dir: /e2e
    volumes:
      - ./webapp:/e2e