name: Dockerized tests

on:
  push:
    branches:
      - docker-compose-for-dev
  pull_request:
    branches: [docker-compose-for-dev]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: run docker compose 
        run: docker-compose -f docker-compose.dev.yml up --build
    
