name: Scheduled Check

on:
  push:
    branches:
      - improve-healthcheck
  schedule:
    - cron:  '30 17 * * 3,6'

jobs:
  scheduled_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the github actions 
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://orcasound.github.io/orcaal/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: "grep matching pattern"
        run: |
         # Everything works fine
          echo "foo" | grep "foo"
      - name: Check postgres database
        run: |
          sudo apt-get install -y nmap
          echo $(nmap -p ${{ secrets.POSTGRES_PORT }} ${{ secrets.LIGHTSAIL_IP }}) | grep postgresql
      - name: Check lightsail instance
        run: |
          echo $(curl ${{ secrets.LIGHTSAIL_IP }}) | grep "Active Learning API is running!"
